SportsStore.WebApp/Controllers/ProductsController.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebApp.Controllers
{
    public class ProductsController : Controller
    {
        private IProductCatalog _catalog;

        public ProductsController(IProductCatalog catalog)
        {
            _catalog = catalog;
        }

        public ActionResult List()
        {
            return View(_catalog.ProductList);
        }

        public ActionResult FilterProducts(string productFilter)
        {
            if (String.IsNullOrEmpty(productFilter))
            {
                return View("List", _catalog.ProductList);
            }
            else
            {
                //ask the product catalog to provide a filtered list of products
                ProductCategory userSelectedCategory = (ProductCategory)Enum.Parse(typeof(ProductCategory), productFilter);

                //use a lambda expression define and use an anoynmous method that 
                //compares the product category with the user selected category
                return View("List", _catalog.FilterProducts(prod => prod.Category == userSelectedCategory));
            }
        }
    }
}

SportsStore.WebApp/Controllers/ShoppingController.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebApp.Controllers
{
    public class ShoppingController : Controller
    {
        //using a constant to identify state objects is a best practice as it
        //is typesafe and avoids any possible missspelling of the text identifier
        private const string SHOPPING_CART_SESSION_OBJ = "ShoppingCart";

        private IProductCatalog _catalog;

        public ShoppingController(IProductCatalog catalog)
        {
            _catalog = catalog;
        }

        public ShoppingCart ShoppingCart
        {
            get
            {
                ShoppingCart cart = Session[SHOPPING_CART_SESSION_OBJ] as ShoppingCart;
                if (cart == null)
                {
                    cart = new ShoppingCart();
                    Session[SHOPPING_CART_SESSION_OBJ] = cart;
                }
                return cart;
            }
        }

        public ActionResult Index(string returnUrl)
        {
            //pass the returnUrl receives through the redirect to the view using
            //the ViewBag object as the model for the page is the shopping cart
            ViewBag.ReturnUrl = returnUrl;

            //return the Index view bound to the shopping cart
            return View(this.ShoppingCart);
        }

        public ActionResult AddToCart(int productId, string returnUrl)
        {
            //obtain the product using a LINQ query extension method (FirstOrDefault)
            Product prod = _catalog.ProductList.FirstOrDefault(p => p.ProductID == productId);

            //if product exists, add the product to the shopping cart from the user's session
            if (prod != null)
            {                
                this.ShoppingCart.AddProduct(prod, 1);
            }

            //Redirect to the Index action using an HTTP GET to avoid
            //reposting the form data if user refreshes the page which would
            //result in adding the product to the shopping cart twice
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore.WebApp/Views/Products/List.cshtml
@using SportsStore.Domain.Entities
@model IEnumerable<Product>

<div>
    <p>
        @using (Html.BeginForm("FilterProducts", "Products"))
        {
            @:Filter By: @Html.DropDownList("ProductFilter",
                                    new SelectList(Enum.GetNames(typeof(ProductCategory))),
                                    "Show All")
            <input type="submit" value="Apply Filter"/>
        }
    </p>
</div>
<div> 
    @foreach (Product prod in Model)
    {
        <div>
            <h3>@prod.Name</h3>
            @prod.Description
            <h4>@prod.Price.ToString("c")</h4>
            <p>
                @using (Html.BeginForm("AddToCart", "Shopping"))
                {
                    @Html.Hidden("ProductID", prod.ProductID)
                    @Html.Hidden("ReturnUrl", Request.Url.PathAndQuery)
                    <input type="submit" value="Add to Cart" />
                }
            </p>
        </div>
    }
</div>